language: node_js

cache: npm

install:
  - npm install
  - npm install -g adapt-cli

script:
  - grunt build

deploy:
  local_dir: build
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
