language: node_js

node_js:
  - node
  
cache: npm

install:
  - rm .gitignore
  - npm install adapt-cli -g
  - npm install grunt-cli -g
  - adapt install -l

script:
  - grunt build

deploy:
  local_dir: build
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
